name: Deploy to GitHub Pages Next

on:
  push:
    branches:
      - dev
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
                    
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Build website
        env:
          COMMIT: ${{ github.sha }}
          VITE_APP_DOMAIN: https://digitalwayhk.github.io/movie-web-build
        run: pnpm run build:pwa

      - name: Publish
        uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-repository-username: 'digitalwayhk'
          destination-repository-name: 'movie-web-build'
          destination-github-username: 'dalveytech-vincent'
          target-branch: 'main'
          user-email: vincent@dalveytech.com
